In [32]:
pip install langchain_community langchain_openai langchain

Requirement already satisfied: langchain_community in c:\users\iqbal\anaconda3\lib\site-packages (0.4.1)
Requirement already satisfied: langchain_openai in c:\users\iqbal\anaconda3\lib\site-packages (1.1.11)
Collecting langchain
  Downloading langchain-1.2.12-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (1.2.18)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (1.0.2)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (2.0.30)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (6.0.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (3.9.5)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (8.2.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (0.7.16)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_community) (1.26.4)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_openai) (2.26.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain_openai) (0.12.0)
Collecting langgraph<1.2.0,>=1.1.1 (from langchain)
  Downloading langgraph-1.1.1-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain) (2.12.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\iqbal\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\iqbal\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\iqbal\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\iqbal\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\iqbal\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.9.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\iqbal\anaconda3\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\iqbal\anaconda3\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain_community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain_community) (1.1.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (23.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain_community) (0.14.1)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.8 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_prebuilt-1.0.8-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.2.0,>=1.1.1->langchain)
  Downloading langgraph_sdk-0.3.11-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\iqbal\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\iqbal\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\iqbal\anaconda3\lib\site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (4.2.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\iqbal\anaconda3\lib\site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\iqbal\anaconda3\lib\site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (0.13.0)
Requirement already satisfied: sniffio in c:\users\iqbal\anaconda3\lib\site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\iqbal\anaconda3\lib\site-packages (from openai<3.0.0,>=2.26.0->langchain_openai) (4.66.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\iqbal\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\iqbal\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\iqbal\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\iqbal\anaconda3\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.21.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\iqbal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iqbal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\iqbal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iqbal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.1.4)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\iqbal\anaconda3\lib\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain_community) (3.0.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\iqbal\anaconda3\lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain_openai) (2023.10.3)
Requirement already satisfied: httpcore==1.* in c:\users\iqbal\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\iqbal\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\iqbal\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain_community) (2.1)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.1->langchain)
  Downloading ormsgpack-1.12.2-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
Requirement already satisfied: colorama in c:\users\iqbal\anaconda3\lib\site-packages (from tqdm>4->openai<3.0.0,>=2.26.0->langchain_openai) (0.4.6)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\iqbal\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain_community) (1.0.0)
Downloading langchain-1.2.12-py3-none-any.whl (112 kB)
   ---------------------------------------- 0.0/112.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/112.4 kB ? eta -:--:--
   ---------- ----------------------------- 30.7/112.4 kB ? eta -:--:--
   --------------------- ------------------ 61.4/112.4 kB 1.1 MB/s eta 0:00:01
   -------------------------------- ------- 92.2/112.4 kB 1.1 MB/s eta 0:00:01
   -------------------------------- ------- 92.2/112.4 kB 1.1 MB/s eta 0:00:01
   -------------------------------------- 112.4/112.4 kB 654.7 kB/s eta 0:00:00
Downloading langgraph-1.1.1-py3-none-any.whl (167 kB)
   ---------------------------------------- 0.0/167.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/167.5 kB ? eta -:--:--
   ------------------- -------------------- 81.9/167.5 kB ? eta -:--:--
   -------------------------- ------------- 112.6/167.5 kB 3.3 MB/s eta 0:00:01
   -------------------------- ------------- 112.6/167.5 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 167.5/167.5 kB 1.1 MB/s eta 0:00:00
Downloading langgraph_checkpoint-4.0.1-py3-none-any.whl (50 kB)
   ---------------------------------------- 0.0/50.5 kB ? eta -:--:--
   -------- ------------------------------- 10.2/50.5 kB ? eta -:--:--
   ------------------------ --------------- 30.7/50.5 kB 325.1 kB/s eta 0:00:01
   ---------------------------------------- 50.5/50.5 kB 368.9 kB/s eta 0:00:00
Downloading langgraph_prebuilt-1.0.8-py3-none-any.whl (35 kB)
Downloading langgraph_sdk-0.3.11-py3-none-any.whl (94 kB)
   ---------------------------------------- 0.0/94.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/94.9 kB ? eta -:--:--
   ---- ----------------------------------- 10.2/94.9 kB ? eta -:--:--
   ------------ --------------------------- 30.7/94.9 kB 640.0 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ----------------- ---------------------- 41.0/94.9 kB 326.8 kB/s eta 0:00:01
   ---------------------------------------- 94.9/94.9 kB 208.0 kB/s eta 0:00:00
Downloading ormsgpack-1.12.2-cp312-cp312-win_amd64.whl (117 kB)
   ---------------------------------------- 0.0/117.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/117.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/117.5 kB ? eta -:--:--
   --- ------------------------------------ 10.2/117.5 kB ? eta -:--:--
   --- ------------------------------------ 10.2/117.5 kB ? eta -:--:--
   ---------- ---------------------------- 30.7/117.5 kB 262.6 kB/s eta 0:00:01
   ---------- ---------------------------- 30.7/117.5 kB 262.6 kB/s eta 0:00:01
   ---------- ---------------------------- 30.7/117.5 kB 262.6 kB/s eta 0:00:01
   ------------- ------------------------- 41.0/117.5 kB 130.7 kB/s eta 0:00:01
   -------------------- ------------------ 61.4/117.5 kB 204.8 kB/s eta 0:00:01
   -------------------- ------------------ 61.4/117.5 kB 204.8 kB/s eta 0:00:01
   --------------------------- ----------- 81.9/117.5 kB 183.3 kB/s eta 0:00:01
   --------------------------- ----------- 81.9/117.5 kB 183.3 kB/s eta 0:00:01
   --------------------------------- ---- 102.4/117.5 kB 210.4 kB/s eta 0:00:01
   -------------------------------------- 117.5/117.5 kB 207.8 kB/s eta 0:00:00
Installing collected packages: ormsgpack, langgraph-sdk, langgraph-checkpoint, langgraph-prebuilt, langgraph, langchain
Successfully installed langchain-1.2.12 langgraph-1.1.1 langgraph-checkpoint-4.0.1 langgraph-prebuilt-1.0.8 langgraph-sdk-0.3.11 ormsgpack-1.12.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
#from pyprojroot import here

In [4]:
df1=pd.read_csv(r'data\CSV_xlsx\heart.csv')
df2=pd.read_csv(r'data\CSV_xlsx\The_Cancer_data_1500_V2.csv')
df3=pd.read_csv(r'data\CSV_xlsx\diabetes.csv')

In [5]:
print(df1.shape)
print(df1.head())

(1025, 14)
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2
1   53    1   0       140   203    1        0      155      1      3.1      0
2   70    1   0       145   174    0        1      125      1      2.6      0
3   61    1   0       148   203    0        1      161      0      0.0      2
4   62    0   0       138   294    1        1      106      0      1.9      1

   ca  thal  target
0   2     3       0
1   0     3       0
2   0     3       0
3   1     3       0
4   3     2       0

In [6]:
print(df2.shape)
print(df2.head())

(1500, 9)
   Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0   58       1  16.085313        0            1          8.146251
1   71       0  30.828784        0            1          9.361630
2   48       1  38.785084        0            2          5.135179
3   34       0  30.040296        0            0          9.502792
4   62       1  35.479721        0            0          5.356890

   AlcoholIntake  CancerHistory  Diagnosis
0       4.148219              1          1
1       3.519683              0          0
2       4.728368              0          1
3       2.044636              0          0
4       3.309849              0          1

In [7]:
print(df3.shape)
print(df3.head())

(768, 9)
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [8]:
from langchain_community.utilities import SQLDatabase
from sqlalchemy import create_engine
data_dir= 'data'
#db_path = str(here("data")) + "/test_sqldb.db"
#db_path = f"sqlite:///{data_dir}/test_sqldb.db"
db_path1 = f"sqlite:///{data_dir}/heart_disease.db"
db_path2 = f"sqlite:///{data_dir}/cancer.db"
db_path3 = f"sqlite:///{data_dir}/diabetes.db"

engine1 = create_engine(db_path1)
engine2 = create_engine(db_path2)
engine3 = create_engine(db_path3)
# df.to_sql("titanic", engine, index=False)

In [9]:
df1.to_sql("heart_disease", engine1, index=False, if_exists="replace")

1025

In [10]:
df2.to_sql("cancer", engine2, index=False, if_exists="replace")

1500

In [11]:
df3.to_sql("diabetes", engine3, index=False, if_exists="replace")

768

In [12]:
db1 = SQLDatabase(engine=engine1)
db2 = SQLDatabase(engine=engine2)
db3 = SQLDatabase(engine=engine3)

In [13]:
print(db1.dialect)
print(db2.dialect)
print(db3.dialect)

sqlite
sqlite
sqlite

In [14]:
print(db1.get_usable_table_names())
print(db2.get_usable_table_names())
print(db3.get_usable_table_names())

['heart_disease']
['cancer']
['diabetes']

In [15]:
db1.run("SELECT * FROM heart_disease where age>50;")

'[(52, 1, 0, 125, 212, 0, 1, 168, 0, 1.0, 2, 2, 3, 0), (53, 1, 0, 140, 203, 1, 0, 155, 1, 3.1, 0, 0, 3, 0), (70, 1, 0, 145, 174, 0, 1, 125, 1, 2.6, 0, 0, 3, 0), (61, 1, 0, 148, 203, 0, 1, 161, 0, 0.0, 2, 1, 3, 0), (62, 0, 0, 138, 294, 1, 1, 106, 0, 1.9, 1, 3, 2, 0), (58, 0, 0, 100, 248, 0, 0, 122, 0, 1.0, 1, 0, 2, 1), (58, 1, 0, 114, 318, 0, 2, 140, 0, 4.4, 0, 3, 1, 0), (55, 1, 0, 160, 289, 0, 0, 145, 1, 0.8, 1, 1, 3, 0), (54, 1, 0, 122, 286, 0, 0, 116, 1, 3.2, 1, 2, 2, 0), (71, 0, 0, 112, 149, 0, 1, 125, 0, 1.6, 1, 0, 2, 1), (51, 1, 0, 140, 298, 0, 1, 122, 1, 4.2, 1, 3, 3, 0), (52, 1, 0, 128, 204, 1, 1, 156, 1, 1.0, 1, 0, 0, 0), (51, 0, 2, 140, 308, 0, 0, 142, 0, 1.5, 2, 1, 2, 1), (54, 1, 0, 124, 266, 0, 0, 109, 1, 2.2, 1, 1, 3, 0), (58, 1, 2, 140, 211, 1, 0, 165, 0, 0.0, 2, 0, 2, 1), (60, 1, 2, 140, 185, 0, 0, 155, 0, 3.0, 1, 0, 2, 0), (67, 0, 0, 106, 223, 0, 1, 142, 0, 0.3, 2, 2, 2, 1), (63, 0, 2, 135, 252, 0, 0, 172, 0, 0.0, 2, 0, 2, 1), (61, 0, 0, 145, 307, 0, 0, 146, 1, 1.0, 1, 0, 3, 0), (58, 0, 1, 136, 319, 1, 0, 152, 0, 0.0, 2, 2, 2, 0), (56, 1, 2, 130, 256, 1, 0, 142, 1, 0.6, 1, 1, 1, 0), (55, 0, 0, 180, 327, 0, 2, 117, 1, 3.4, 1, 0, 2, 0), (57, 1, 0, 130, 131, 0, 1, 115, 1, 1.2, 1, 1, 3, 0), (70, 1, 2, 160, 269, 0, 1, 112, 1, 2.9, 1, 1, 3, 0), (51, 1, 3, 125, 213, 0, 0, 125, 1, 1.4, 2, 1, 2, 1), (59, 1, 0, 138, 271, 0, 0, 182, 0, 0.0, 2, 0, 2, 1), (64, 1, 0, 128, 263, 0, 1, 105, 1, 0.2, 1, 1, 3, 1), (57, 1, 2, 128, 229, 0, 0, 150, 0, 0.4, 1, 1, 3, 0), (65, 0, 2, 160, 360, 0, 0, 151, 0, 0.8, 2, 0, 2, 1), (54, 1, 2, 120, 258, 0, 0, 147, 0, 0.4, 1, 0, 3, 1), (61, 0, 0, 130, 330, 0, 0, 169, 0, 0.0, 2, 0, 2, 0), (55, 0, 1, 132, 342, 0, 1, 166, 0, 1.2, 2, 0, 2, 1), (66, 0, 0, 178, 228, 1, 1, 165, 1, 1.0, 1, 2, 3, 0), (66, 0, 2, 146, 278, 0, 0, 152, 0, 0.0, 1, 1, 2, 1), (60, 1, 0, 117, 230, 1, 1, 160, 1, 1.4, 2, 2, 3, 0), (58, 0, 3, 150, 283, 1, 0, 162, 0, 1.0, 2, 0, 2, 1), (57, 0, 0, 140, 241, 0, 1, 123, 1, 0.2, 1, 0, 3, 0), (55, 1, 0, 140, 217, 0, 1, 111, 1, 5.6, 0, 0, 3, 0), (55, 1, 0, 140, 217, 0, 1, 111, 1, 5.6, 0, 0, 3, 0), (56, 1, 3, 120, 193, 0, 0, 162, 0, 1.9, 1, 0, 3, 1), (67, 1, 2, 152, 212, 0, 0, 150, 0, 0.8, 1, 0, 3, 0), (57, 1, 1, 154, 232, 0, 0, 164, 0, 0.0, 2, 1, 2, 0), (66, 0, 2, 146, 278, 0, 0, 152, 0, 0.0, 1, 1, 2, 1), (67, 1, 0, 100, 299, 0, 0, 125, 1, 0.9, 1, 2, 2, 0), (59, 1, 2, 150, 212, 1, 1, 157, 0, 1.6, 2, 0, 2, 1), (59, 1, 3, 170, 288, 0, 0, 159, 0, 0.2, 1, 0, 3, 0), (53, 1, 2, 130, 197, 1, 0, 152, 0, 1.2, 0, 0, 2, 1), (62, 0, 0, 160, 164, 0, 0, 145, 0, 6.2, 0, 3, 3, 0), (59, 1, 0, 170, 326, 0, 0, 140, 1, 3.4, 0, 0, 3, 0), (61, 1, 0, 140, 207, 0, 0, 138, 1, 1.9, 2, 1, 3, 0), (56, 1, 0, 125, 249, 1, 0, 144, 1, 1.2, 1, 1, 2, 0), (59, 1, 0, 140, 177, 0, 1, 162, 1, 0.0, 2, 1, 3, 0), (63, 1, 0, 140, 187, 0, 0, 144, 1, 4.0, 2, 2, 3, 0), (52, 1, 1, 134, 201, 0, 1, 158, 0, 0.8, 2, 1, 2, 1), (52, 1, 1, 134, 201, 0, 1, 158, 0, 0.8, 2, 1, 2, 1), (58, 1, 2, 140, 211, 1, 0, 165, 0, 0.0, 2, 0, 2, 1), (59, 0, 0, 174, 249, 0, 1, 143, 1, 0.0, 1, 0, 2, 0), (62, 0, 0, 140, 268, 0, 0, 160, 0, 3.6, 0, 2, 2, 0), (68, 1, 0, 144, 193, 1, 1, 141, 0, 3.4, 1, 2, 3, 0), (54, 0, 2, 108, 267, 0, 0, 167, 0, 0.0, 2, 0, 2, 1), (62, 0, 0, 124, 209, 0, 1, 163, 0, 0.0, 2, 0, 2, 1), (63, 1, 0, 140, 187, 0, 0, 144, 1, 4.0, 2, 2, 3, 0), (62, 1, 1, 128, 208, 1, 0, 140, 0, 0.0, 2, 0, 2, 1), (57, 0, 0, 128, 303, 0, 0, 159, 0, 0.0, 2, 1, 2, 1), (53, 1, 0, 123, 282, 0, 1, 95, 1, 2.0, 1, 2, 3, 0), (65, 1, 0, 110, 248, 0, 0, 158, 0, 0.6, 2, 2, 1, 0), (76, 0, 2, 140, 197, 0, 2, 116, 0, 1.1, 1, 0, 2, 1), (57, 1, 2, 150, 126, 1, 1, 173, 0, 0.2, 2, 1, 3, 1), (54, 1, 1, 108, 309, 0, 1, 156, 0, 0.0, 2, 0, 3, 1), (52, 1, 3, 118, 186, 0, 0, 190, 0, 0.0, 1, 0, 1, 1), (51, 1, 0, 140, 299, 0, 1, 173, 1, 1.6, 2, 0, 3, 0), (62, 1, 1, 120, 281, 0, 0, 103, 0, 1.4, 1, 1, 3, 0), (54, 1, 0, 110, 206, 0, 0, 108, 1, 0.0, 1, 1, 2, 0), (53, 1, 0, 142, 226, 0, 0, 111, 1, 0.0, 2, 0, 3, 1), (57, 1, 0, 110, 335, 0, 1, 143, 1, 3.0, 1, 1, 3, 0), (59, 1, 2, 126, 218, 1, 1, 134, 0, 2.2, 1, 1, 1, 0), (61, 0, 0, 145, 307, 0, 0, 146, 1, 1.0, 1, 0, 3, 0), (63, 1, 0, 130, 254, 0, 0, 147, 0, 1.4, 1, 1, 3, 0), (54, 1, 1, 108, 309, 0, 1, 156, 0, 0.0, 2, 0, 3, 1), (60, 1, 0, 145, 282, 0, 0, 142, 1, 2.8, 1, 2, 3, 0), (65, 0, 2, 140, 417, 1, 0, 157, 0, 0.8, 2, 1, 2, 1), (61, 1, 0, 120, 260, 0, 1, 140, 1, 3.6, 1, 1, 3, 0), (60, 0, 3, 150, 240, 0, 1, 171, 0, 0.9, 2, 0, 2, 1), (66, 1, 0, 120, 302, 0, 0, 151, 0, 0.4, 1, 0, 2, 1), (53, 1, 2, 130, 197, 1, 0, 152, 0, 1.2, 0, 0, 2, 1), (52, 1, 2, 138, 223, 0, 1, 169, 0, 0.0, 2, 4, 2, 1), (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1), (60, 0, 3, 150, 240, 0, 1, 171, 0, 0.9, 2, 0, 2, 1), (51, 0, 2, 130, 256, 0, 0, 149, 0, 0.5, 2, 0, 2, 1), (54, 1, 1, 108, 309, 0, 1, 156, 0, 0.0, 2, 0, 3, 1), (58, 0, 0, 170, 225, 1, 0, 146, 1, 2.8, 1, 2, 1, 0), (55, 0, 1, 132, 342, 0, 1, 166, 0, 1.2, 2, 0, 2, 1), (64, 0, 0, 180, 325, 0, 1, 154, 1, 0.0, 2, 0, 2, 1), (57, 1, 0, 152, 274, 0, 1, 88, 1, 1.2, 1, 1, 3, 0), (63, 0, 0, 124, 197, 0, 1, 136, 1, 0.0, 1, 0, 2, 0), (61, 1, 3, 134, 234, 0, 1, 145, 0, 2.6, 1, 2, 2, 0), (51, 0, 2, 120, 295, 0, 0, 157, 0, 0.6, 2, 0, 2, 1), (52, 1, 3, 152, 298, 1, 1, 178, 0, 1.2, 1, 0, 3, 1), (58, 1, 0, 114, 318, 0, 2, 140, 0, 4.4, 0, 3, 1, 0), (54, 1, 1, 192, 283, 0, 0, 195, 0, 0.0, 2, 1, 3, 0), (58, 1, 0, 125, 300, 0, 0, 171, 0, 0.0, 2, 2, 3, 0), (54, 1, 2, 120, 258, 0, 0, 147, 0, 0.4, 1, 0, 3, 1), (63, 1, 0, 130, 330, 1, 0, 132, 1, 1.8, 2, 3, 3, 0), (54, 1, 1, 108, 309, 0, 1, 156, 0, 0.0, 2, 0, 3, 1), (54, 1, 2, 120, 258, 0, 0, 147, 0, 0.4, 1, 0, 3, 1), (67, 0, 2, 115, 564, 0, 0, 160, 0, 1.6, 1, 0, 3, 1), (77, 1, 0, 125, 304, 0, 0, 162, 1, 0.0, 2, 3, 2, 0), (51, 1, 2, 100, 222, 0, 1, 143, 1, 1.2, 1, 0, 2, 1), (77, 1, 0, 125, 304, 0, 0, 162, 1, 0.0, 2, 3, 2, 0), (56, 1, 0, 125, 249, 1, 0, 144, 1, 1.2, 1, 1, 2, 0), (59, 1, 0, 170, 326, 0, 0, 140, 1, 3.4, 0, 0, 3, 0), (56, 1, 0, 132, 184, 0, 0, 105, 1, 2.1, 1, 1, 1, 0), (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1), (56, 1, 0, 130, 283, 1, 0, 103, 1, 1.6, 0, 0, 3, 0), (56, 1, 1, 120, 240, 0, 1, 169, 0, 0.0, 0, 0, 2, 1), (54, 1, 0, 110, 239, 0, 1, 126, 1, 2.8, 1, 1, 3, 0), (56, 0, 0, 200, 288, 1, 0, 133, 1, 4.0, 0, 2, 3, 0), (56, 1, 0, 130, 283, 1, 0, 103, 1, 1.6, 0, 0, 3, 0), (64, 1, 0, 120, 246, 0, 0, 96, 1, 2.2, 0, 1, 2, 0), (56, 0, 0, 134, 409, 0, 0, 150, 1, 1.9, 1, 2, 3, 0), (63, 1, 0, 140, 187, 0, 0, 144, 1, 4.0, 2, 2, 3, 0), (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1), (60, 1, 0, 140, 293, 0, 0, 170, 0, 1.2, 1, 2, 3, 0), (57, 1, 0, 165, 289, 1, 0, 124, 0, 1.0, 1, 3, 3, 0), (56, 1, 0, 125, 249, 1, 0, 144, 1, 1.2, 1, 1, 2, 0), (63, 1, 0, 130, 254, 0, 0, 147, 0, 1.4, 1, 1, 3, 0), (64, 1, 2, 125, 309, 0, 1, 131, 1, 1.8, 1, 0, 3, 0), (56, 1, 1, 130, 221, 0, 0, 163, 0, 0.0, 2, 0, 3, 1), (67, 0, 2, 115, 564, 0, 0, 160, 0, 1.6, 1, 0, 3, 1), (69, 1, 3, 160, 234, 1, 0, 131, 0, 0.1, 1, 1, 2, 1), (67, 1, 0, 160, 286, 0, 0, 108, 1, 1.5, 1, 3, 2, 0), (59, 1, 2, 150, 212, 1, 1, 157, 0, 1.6, 2, 0, 2, 1), (58, 1, 0, 100, 234, 0, 1, 156, 0, 0.1, 2, 1, 3, 0), (60, 0, 2, 102, 318, 0, 1, 160, 0, 0.0, 2, 1, 2, 1), (62, 0, 0, 124, 209, 0, 1, 163, 0, 0.0, 2, 0, 2, 1), (52, 1, 3, 152, 298, 1, 1, 178, 0, 1.2, 1, 0, 3, 1), (64, 1, 3, 170, 227, 0, 0, 155, 0, 0.6, 1, 0, 3, 1), (66, 0, 2, 146, 278, 0, 0, 152, 0, 0.0, 1, 1, 2, 1), (59, 1, 2, 126, 218, 1, 1, 134, 0, 2.2, 1, 1, 1, 0), (62, 1, 1, 120, 281, 0, 0, 103, 0, 1.4, 1, 1, 3, 0), (67, 1, 0, 100, 299, 0, 0, 125, 1, 0.9, 1, 2, 2, 0), (65, 1, 0, 135, 254, 0, 0, 127, 0, 2.8, 1, 1, 3, 0), (54, 1, 0, 122, 286, 0, 0, 116, 1, 3.2, 1, 2, 2, 0), (57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1, 1, 2, 0), (63, 1, 0, 130, 254, 0, 0, 147, 0, 1.4, 1, 1, 3, 0), (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1), (51, 1, 0, 140, 261, 0, 0, 186, 1, 0.0, 2, 0, 2, 1), (54, 1, 2, 150, 232, 0, 0, 165, 0, 1.6, 2, 0, 3, 1), (52, 1, 1, 128, 205, 1, 1, 184, 0, 0.0, 2, 0, 2, 1), (66, 0, 0, 178, 228, 1, 1, 165, 1, 1.0, 1, 2, 3, 0), (58, 1, 0, 125, 300, 0, 0, 171, 0, 0.0, 2, 2, 3, 0), (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1), (60, 1, 0, 125, 258, 0, 0, 141, 1, 2.8, 1, 1, 3, 0), (64, 1, 3, 170, 227, 0, 0, 155, 0, 0.6, 1, 0, 3, 1), (57, 1, 1, 124, 261, 0, 1, 141, 0, 0.3, 2, 0, 3, 0), (60, 1, 0, 117, 230, 1, 1, 160, 1, 1.4, 2, 2, 3, 0), (62, 0, 0, 150, 244, 0, 1, 154, 1, 1.4, 1, 0, 2, 0), (54, 0, 1, 132, 288, 1, 0, 159, 1, 0.0, 2, 1, 2, 1), (67, 1, 2, 152, 212, 0, 0, 150, 0, 0.8, 1, 0, 3, 0), (60, 1, 2, 140, 185, 0, 0, 155, 0, 3.0, 1, 0, 2, 0), (51, 1, 2, 125, 245, 1, 0, 166, 0, 2.4, 1, 0, 2, 1), (54, 1, 1, 192, 283, 0, 0, 195, 0, 0.0, 2, 1, 3, 0), (55, 1, 0, 132, 353, 0, 1, 132, 1, 1.2, 1, 1, 3, 0), (57, 1, 0, 165, 289, 1, 0, 124, 0, 1.0, 1, 3, 3, 0), (62, 0, 0, 140, 394, 0, 0, 157, 0, 1.2, 1, 0, 2, 1), (64, 0, 0, 180, 325, 0, 1, 154, 1, 0.0, 2, 0, 2, 1), (66, 1, 0, 120, 302, 0, 0, 151, 0, 0.4, 1, 0, 2, 1), (54, 1, 2, 150, 232, 0, 0, 165, 0, 1.6, 2, 0, 3, 1), (55, 0, 1, 132, 342, 0, 1, 166, 0, 1.2, 2, 0, 2, 1), (58, 0, 0, 170, 225, 1, 0, 146, 1, 2.8, 1, 2, 1, 0), (53, 1, 0, 123, 282, 0, 1, 95, 1, 2.0, 1, 2, 3, 0), (67, 1, 0, 120, 237, 0, 1, 71, 0, 1.0, 1, 0, 2, 0), (58, 1, 2, 132, 224, 0, 0, 173, 0, 3.2, 2, 2, 3, 0), (71, 0, 2, 110, 265, 1, 0, 130, 0, 0.0, 2, 1, 2, 1), (54, 1, 0, 110, 206, 0, 0, 108, 1, 0.0, 1, 1, 2, 0), (66, 1, 0, 160, 228, 0, 0, 138, 0, 2.3, 2, 0, 1, 1), (56, 1, 0, 130, 283, 1, 0, 103, 1, 1.6, 0, 0, 3, 0), (57, 1, 0, 132, 207, 0, 1, 168, 1, 0.0, 2, 0, 3, 1), (55, 1, 0, 160, 289, 0, 0, 145, 1, 0.8, 1, 1, 3, 0), (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1), (58, 1, 2, 132, 224, 0, 0, 173, 0, 3.2, 2, 2, 3, 0), (71, 0, 2, 110, 265, 1, 0, 130, 0, 0.0, 2, 1, 2, 1), (64, 0, 2, 140, 313, 0, 1, 133, 0, 0.2, 2, 0, 3, 1), (71, 0, 1, 160, 302, 0, 1, 162, 0, 0.4, 2, 2, 2, 1), (58, 0, 2, 120, 340, 0, 1, 172, 0, 0.0, 2, 0, 2, 1), (52, 1, 2, 138, 223, 0, 1, 169, 0, 0.0, 2, 4, 2, 1), (58, 1, 0, 128, 259, 0, 0, 130, 1, 3.0, 1, 2, 3, 0), (61, 1, 2, 150, 243, 1, 1, 137, 1, 1.0, 1, 0, 2, 1), (59, 1, 2, 150, 212, 1, 1, 157, 0, 1.6, 2, 0, 2, 1), (56, 0, 0, 200, 288, 1, 0, 133, 1, 4.0, 0, 2, 3, 0), (67, 1, 0, 100, 299, 0, 0, 125, 1, 0.9, 1, 2, 2, 0), (67, 1, 0, 120, 237, 0, 1, 71, 0, 1.0, 1, 0, 2, 0), (58, 1, 0, 150, 270, 0, 0, 111, 1, 0.8, 2, 0, 3, 0), (52, 1, 1, 120, 325, 0, 1, 172, 0, 0.2, 2, 0, 2, 1), (51, 1, 2, 94, 227, 0, 1, 154, 1, 0.0, 2, 1, 3, 1), (55, 0, 1, 132, 342, 0, 1, 166, 0, 1.2, 2, 0, 2, 1), (60, 1, 0, 145, 282, 0, 0, 142, 1, 2.8, 1, 2, 3, 0), (52, 0, 2, 136, 196, 0, 0, 169, 0, 0.1, 1, 0, 2, 1), (62, 1, 0, 120, 267, 0, 1, 99, 1, 1.8, 1, 2, 3, 0), (59, 1, 2, 126, 218, 1, 1, 134, 0, 2.2, 1, 1, 1, 0), (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1), (61, 1, 0, 120, 260, 0, 1, 140, 1, 3.6, 1, 1, 3, 0), (70, 1, 2, 160, 269, 0, 1, 112, 1, 2.9, 1, 1, 3, 0), (74, 0, 1, 120, 269, 0, 0, 121, 1, 0.2, 2, 1, 2, 1), (64, 0, 2, 140, 313, 0, 1, 133, 0, 0.2, 2, 0, 3, 1), (63, 0, 2, 135, 252, 0, 0, 172, 0, 0.0, 2, 0, 2, 1), (59, 1, 0, 140, 177, 0, 1, 162, 1, 0.0, 2, 1, 3, 0), (53, 0, 2, 128, 216, 0, 0, 115, 0, 0.0, 2, 0, 0, 1), (53, 0, 0, 130, 264, 0, 0, 143, 0, 0.4, 1, 0, 2, 1), (66, 1, 1, 160, 246, 0, 1, 120, 1, 0.0, 1, 3, 1, 0), (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1), (54, 1, 1, 192, 283, 0, 0, 195, 0, 0.0, 2, 1, 3, 0), (57, 1, 0, 150, 276, 0, 0, 112, 1, 0.6, 1, 1, 1, 0), (70, 1, 0, 130, 322, 0, 0, 109, 0, 2.4, 1, 3, 2, 0), (53, 0, 2, 128, 216, 0, 0, 115, 0, 0.0, 2, 0, 0, 1), (63, 0, 0, 108, 269, 0, 1, 169, 1, 1.8, 1, 2, 2, 0), (54, 0, 2, 110, 214, 0, 1, 158, 0, 1.6, 1, 0, 2, 1), (60, 1, 0, 130, 206, 0, 0, 132, 1, 2.4, 1, 2, 3, 0), (58, 1, 0, 150, 270, 0, 0, 111, 1, 0.8, 2, 0, 3, 0), (57, 1, 2, 150, 126, 1, 1, 173, 0, 0.2, 2, 1, 3, 1), (54, 1, 2, 125, 273, 0, 0, 152, 0, 0.5, 0, 1, 2, 1), (56, 1, 2, 130, 256, 1, 0, 142, 1, 0.6, 1, 1, 1, 0), (60, 1, 0, 130, 253, 0, 1, 144, 1, 1.4, 2, 1, 3, 0), (65, 0, 2, 155, 269, 0, 1, 148, 0, 0.8, 2, 0, 2, 1), (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1), (66, 1, 1, 160, 246, 0, 1, 120, 1, 0.0, 1, 3, 1, 0), (54, 0, 2, 108, 267, 0, 0, 167, 0, 0.0, 2, 0, 2, 1), (62, 0, 2, 130, 263, 0, 1, 97, 0, 1.2, 1, 1, 3, 0), (66, 1, 0, 120, 302, 0, 0, 151, 0, 0.4, 1, 0, 2, 1), (57, 1, 0, 110, 335, 0, 1, 143, 1, 3.0, 1, 1, 3, 0), (57, 1, 0, 110, 201, 0, 1, 126, 1, 1.5, 1, 0, 1, 1), (57, 1, 1, 124, 261, 0, 1, 141, 0, 0.3, 2, 0, 3, 0), (59, 1, 0, 164, 176, 1, 0, 90, 0, 1.0, 1, 2, 1, 0), (67, 1, 0, 160, 286, 0, 0, 108, 1, 1.5, 1, 3, 2, 0), (59, 1, 3, 134, 204, 0, 1, 162, 0, 0.8, 2, 2, 2, 0), (53, 0, 2, 128, 216, 0, 0, 115, 0, 0.0, 2, 0, 0, 1), (62, 1, 2, 130, 231, 0, 1, 146, 0, 1.8, 1, 3, 3, 1), (53, 1, 2, 130, 246, 1, 0, 173, 0, 0.0, 2, 3, 2, 1), (57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1, 1, 2, 0), (53, 1, 2, 130, 246, 1, 0, 173, 0, 0.0, 2, 3, 2, 1), (58, 1, 2, 112, 230, 0, 0, 165, 0, 2.5, 1, 1, 3, 0), (58, 1, 2, 105, 240, 0, 0, 154, 1, 0.6, 1, 0, 3, 1), (51, 1, 2, 110, 175, 0, 1, 123, 0, 0.6, 2, 0, 2, 1), (55, 1, 0, 132, 353, 0, 1, 132, 1, 1.2, 1, 1, 3, 0), (54, 0, 2, 110, 214, 0, 1, 158, 0, 1.6, 1, 0, 2, 1), (58, 1, 1, 120, 284, 0, 0, 160, 0, 1.8, 1, 0, 2, 0), (66, 1, 0, 160, 228, 0, 0, 138, 0, 2.3, 2, 0, 1, 1), (59, 1, 1, 140, 221, 0, 1, 164, 1, 0.0, 2, 0, 2, 1), (64, 0, 0, 130, 303, 0, 1, 122, 0, 2.0, 1, 2, 2, 1), (67, 1, 0, 120, 237, 0, 1, 71, 0, 1.0, 1, 0, 2, 0), (52, 1, 3, 118, 186, 0, 0, 190, 0, 0.0, 1, 0, 1, 1), (58, 1, 0, 146, 218, 0, 1, 105, 0, 2.0, 1, 1, 3, 0), (58, 1, 2, 132, 224, 0, 0, 173, 0, 3.2, 2, 2, 3, 0), (59, 1, 0, 110, 239, 0, 0, 142, 1, 1.2, 1, 1, 3, 0), (58, 1, 0, 150, 270, 0, 0, 111, 1, 0.8, 2, 0, 3, 0), (51, 1, 2, 110, 175, 0, 1, 123, 0, 0.6, 2, 0, 2, 1), (77, 1, 0, 125, 304, 0, 0, 162, 1, 0.0, 2, 3, 2, 0), (64, 1, 0, 120, 246, 0, 0, 96, 1, 2.2, 0, 1, 2, 0), (63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1), (58, 0, 1, 136, 319, 1, 0, 152, 0, 0.0, 2, 2, 2, 0), (51, 1, 2, 110, 175, 0, 1, 123, 0, 0.6, 2, 0, 2, 1), (62, 0, 0, 160, 164, 0, 0, 145, 0, 6.2, 0, 3, 3, 0), (63, 1, 0, 130, 330, 1, 0, 132, 1, 1.8, 2, 3, 3, 0), (66, 0, 2, 146, 278, 0, 0, 152, 0, 0.0, 1, 1, 2, 1), (68, 1, 2, 180, 274, 1, 0, 150, 1, 1.6, 1, 0, 3, 0), (66, 1, 0, 160, 228, 0, 0, 138, 0, 2.3, 2, 0, 1, 1), (63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1), (71, 0, 0, 112, 149, 0, 1, 125, 0, 1.6, 1, 0, 2, 1), (70, 1, 1, 156, 245, 0, 0, 143, 0, 0.0, 2, 0, 2, 1), (61, 1, 0, 140, 207, 0, 0, 138, 1, 1.9, 2, 1, 3, 0), (56, 1, 2, 130, 256, 1, 0, 142, 1, 0.6, 1, 1, 1, 0), (58, 1, 2, 140, 211, 1, 0, 165, 0, 0.0, 2, 0, 2, 1), (58, 1, 0, 100, 234, 0, 1, 156, 0, 0.1, 2, 1, 3, 0), (56, 1, 0, 125, 249, 1, 0, 144, 1, 1.2, 1, 1, 2, 0), (57, 1, 0, 150, 276, 0, 0, 112, 1, 0.6, 1, 1, 1, 0), (70, 1, 0, 130, 322, 0, 0, 109, 0, 2.4, 1, 3, 2, 0), (59, 1, 3, 170, 288, 0, 0, 159, 0, 0.2, 1, 0, 3, 0), (54, 1, 2, 125, 273, 0, 0, 152, 0, 0.5, 0, 1, 2, 1), (52, 1, 2, 138, 223, 0, 1, 169, 0, 0.0, 2, 4, 2, 1), (62, 0, 0, 124, 209, 0, 1, 163, 0, 0.0, 2, 0, 2, 1), (65, 0, 2, 160, 360, 0, 0, 151, 0, 0.8, 2, 0, 2, 1), (57, 0, 0, 128, 303, 0, 0, 159, 0, 0.0, 2, 1, 2, 1), (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1), (58, 0, 1, 136, 319, 1, 0, 152, 0, 0.0, 2, 2, 2, 0), (51, 0, 0, 130, 305, 0, 1, 142, 1, 1.2, 1, 0, 3, 0), (54, 0, 2, 160, 201, 0, 1, 163, 0, 0.0, 2, 1, 2, 1), (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1), (67, 1, 2, 152, 212, 0, 0, 150, 0, 0.8, 1, 0, 3, 0), (65, 0, 0, 150, 225, 0, 0, 114, 0, 1.0, 1, 3, 3, 0), (60, 0, 2, 102, 318, 0, 1, 160, 0, 0.0, 2, 1, 2, 1), (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1), (59, 0, 0, 174, 249, 0, 1, 143, 1, 0.0, 1, 0, 2, 0), (67, 1, 0, 120, 229, 0, 0, 129, 1, 2.6, 1, 2, 3, 0), (58, 1, 1, 120, 284, 0, 0, 160, 0, 1.8, 1, 0, 2, 0), (62, 0, 0, 150, 244, 0, 1, 154, 1, 1.4, 1, 0, 2, 0), (60, 1, 0, 140, 293, 0, 0, 170, 0, 1.2, 1, 2, 3, 0), (57, 1, 0, 152, 274, 0, 1, 88, 1, 1.2, 1, 1, 3, 0), (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1), (52, 1, 1, 128, 205, 1, 1, 184, 0, 0.0, 2, 0, 2, 1), (53, 1, 2, 130, 246, 1, 0, 173, 0, 0.0, 2, 3, 2, 1), (55, 1, 0, 160, 289, 0, 0, 145, 1, 0.8, 1, 1, 3, 0), (51, 0, 2, 120, 295, 0, 0, 157, 0, 0.6, 2, 0, 2, 1), (52, 1, 0, 112, 230, 0, 1, 160, 0, 0.0, 2, 1, 2, 0), (63, 0, 0, 150, 407, 0, 0, 154, 0, 4.0, 1, 3, 3, 0), (66, 0, 0, 178, 228, 1, 1, 165, 1, 1.0, 1, 2, 3, 0), (65, 0, 0, 150, 225, 0, 0, 114, 0, 1.0, 1, 3, 3, 0), (69, 1, 3, 160, 234, 1, 0, 131, 0, 0.1, 1, 1, 2, 1), (51, 1, 0, 140, 261, 0, 0, 186, 1, 0.0, 2, 0, 2, 1), (69, 1, 2, 140, 254, 0, 0, 146, 0, 2.0, 1, 3, 3, 0), (52, 1, 3, 118, 186, 0, 0, 190, 0, 0.0, 1, 0, 1, 1), (67, 0, 2, 115, 564, 0, 0, 160, 0, 1.6, 1, 0, 3, 1), (61, 1, 2, 150, 243, 1, 1, 137, 1, 1.0, 1, 0, 2, 1), (67, 1, 0, 160, 286, 0, 0, 108, 1, 1.5, 1, 3, 2, 0), (60, 0, 3, 150, 240, 0, 1, 171, 0, 0.9, 2, 0, 2, 1), (64, 0, 2, 140, 313, 0, 1, 133, 0, 0.2, 2, 0, 3, 1), (58, 0, 0, 130, 197, 0, 1, 131, 0, 0.6, 1, 0, 2, 1), (57, 1, 2, 150, 126, 1, 1, 173, 0, 0.2, 2, 1, 3, 1), (57, 1, 0, 165, 289, 1, 0, 124, 0, 1.0, 1, 3, 3, 0), (57, 1, 2, 128, 229, 0, 0, 150, 0, 0.4, 1, 1, 3, 0), (58, 1, 0, 128, 216, 0, 0, 131, 1, 2.2, 1, 3, 3, 0), (51, 0, 0, 130, 305, 0, 1, 142, 1, 1.2, 1, 0, 3, 0), (63, 0, 0, 150, 407, 0, 0, 154, 0, 4.0, 1, 3, 3, 0), (51, 1, 0, 140, 298, 0, 1, 122, 1, 4.2, 1, 3, 3, 0), (65, 1, 0, 110, 248, 0, 0, 158, 0, 0.6, 2, 2, 1, 0), (62, 1, 1, 120, 281, 0, 0, 103, 0, 1.4, 1, 1, 3, 0), (65, 1, 0, 135, 254, 0, 0, 127, 0, 2.8, 1, 1, 3, 0), (54, 0, 1, 132, 288, 1, 0, 159, 1, 0.0, 2, 1, 2, 1), (61, 1, 2, 150, 243, 1, 1, 137, 1, 1.0, 1, 0, 2, 1), (57, 0, 0, 128, 303, 0, 0, 159, 0, 0.0, 2, 1, 2, 1), (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1), (64, 1, 2, 125, 309, 0, 1, 131, 1, 1.8, 1, 0, 3, 0), (55, 1, 0, 132, 353, 0, 1, 132, 1, 1.2, 1, 1, 3, 0), (51, 1, 2, 125, 245, 1, 0, 166, 0, 2.4, 1, 0, 2, 1), (59, 1, 0, 135, 234, 0, 1, 161, 0, 0.5, 1, 0, 3, 1), (68, 1, 2, 180, 274, 1, 0, 150, 1, 1.6, 1, 0, 3, 0), (57, 1, 1, 154, 232, 0, 0, 164, 0, 0.0, 2, 1, 2, 0), (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1), (71, 0, 0, 112, 149, 0, 1, 125, 0, 1.6, 1, 0, 2, 1), (61, 1, 0, 120, 260, 0, 1, 140, 1, 3.6, 1, 1, 3, 0), (56, 0, 0, 200, 288, 1, 0, 133, 1, 4.0, 0, 2, 3, 0), (55, 0, 0, 180, 327, 0, 2, 117, 1, 3.4, 1, 0, 2, 0), (54, 0, 1, 132, 288, 1, 0, 159, 1, 0.0, 2, 1, 2, 1), (54, 1, 0, 110, 206, 0, 0, 108, 1, 0.0, 1, 1, 2, 0), (60, 1, 0, 130, 206, 0, 0, 132, 1, 2.4, 1, 2, 3, 0), (61, 1, 0, 148, 203, 0, 1, 161, 0, 0.0, 2, 1, 3, 0), (59, 1, 0, 140, 177, 0, 1, 162, 1, 0.0, 2, 1, 3, 0), (58, 1, 1, 125, 220, 0, 1, 144, 0, 0.4, 1, 4, 3, 1), (67, 0, 2, 152, 277, 0, 1, 172, 0, 0.0, 2, 1, 2, 1), (61, 1, 0, 148, 203, 0, 1, 161, 0, 0.0, 2, 1, 3, 0), (58, 1, 2, 112, 230, 0, 0, 165, 0, 2.5, 1, 1, 3, 0), (51, 0, 2, 130, 256, 0, 0, 149, 0, 0.5, 2, 0, 2, 1), (62, 0, 0, 160, 164, 0, 0, 145, 0, 6.2, 0, 3, 3, 0), (62, 0, 0, 124, 209, 0, 1, 163, 0, 0.0, 2, 0, 2, 1), (59, 1, 3, 178, 270, 0, 0, 145, 0, 4.2, 0, 0, 3, 1), (69, 1, 3, 160, 234, 1, 0, 131, 0, 0.1, 1, 1, 2, 1), (60, 0, 0, 150, 258, 0, 0, 157, 0, 2.6, 1, 2, 3, 0), (65, 0, 2, 155, 269, 0, 1, 148, 0, 0.8, 2, 0, 2, 1), (63, 0, 0, 124, 197, 0, 1, 136, 1, 0.0, 1, 0, 2, 0), (53, 0, 0, 138, 234, 0, 0, 160, 0, 0.0, 2, 0, 2, 1), (54, 0, 2, 108, 267, 0, 0, 167, 0, 0.0, 2, 0, 2, 1), (76, 0, 2, 140, 197, 0, 2, 116, 0, 1.1, 1, 0, 2, 1), (52, 1, 1, 120, 325, 0, 1, 172, 0, 0.2, 2, 0, 2, 1), (64, 1, 3, 170, 227, 0, 0, 155, 0, 0.6, 1, 0, 3, 1), (58, 1, 0, 128, 259, 0, 0, 130, 1, 3.0, 1, 2, 3, 0), (62, 0, 0, 140, 394, 0, 0, 157, 0, 1.2, 1, 0, 2, 1), (59, 1, 3, 134, 204, 0, 1, 162, 0, 0.8, 2, 2, 2, 0), (54, 1, 2, 125, 273, 0, 0, 152, 0, 0.5, 0, 1, 2, 1), (70, 1, 0, 130, 322, 0, 0, 109, 0, 2.4, 1, 3, 2, 0), (67, 0, 0, 106, 223, 0, 1, 142, 0, 0.3, 2, 2, 2, 1), (51, 0, 2, 120, 295, 0, 0, 157, 0, 0.6, 2, 0, 2, 1), (68, 1, 2, 118, 277, 0, 1, 151, 0, 1.0, 2, 1, 3, 1), (69, 1, 2, 140, 254, 0, 0, 146, 0, 2.0, 1, 3, 3, 0), (54, 1, 0, 122, 286, 0, 0, 116, 1, 3.2, 1, 2, 2, 0), (53, 1, 2, 130, 197, 1, 0, 152, 0, 1.2, 0, 0, 2, 1), (58, 1, 0, 100, 234, 0, 1, 156, 0, 0.1, 2, 1, 3, 0), (67, 1, 0, 125, 254, 1, 1, 163, 0, 0.2, 1, 2, 3, 0), (59, 1, 0, 140, 177, 0, 1, 162, 1, 0.0, 2, 1, 3, 0), (67, 1, 0, 120, 237, 0, 1, 71,

In [16]:
df1[df1['age']>50]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,65,1,3,138,282,1,0,174,0,1.4,1,1,2,0
1017,53,1,0,123,282,0,1,95,1,2.0,1,2,3,0
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [17]:
db2.run("SELECT * FROM cancer where age>50;")

'[(58, 1, 16.085313321370478, 0, 1, 8.146250560259173, 4.148219026764642, 1, 1), (71, 0, 30.82878438985056, 0, 1, 9.361630415509964, 3.519683335172577, 0, 0), (62, 1, 35.47972148566976, 0, 0, 5.356889704560298, 3.309849197253171, 0, 1), (80, 1, 20.701994298723317, 0, 0, 8.482031285528954, 3.1529434865427177, 0, 0), (58, 1, 30.274524721274798, 0, 1, 4.719025105645231, 0.9431612321203742, 1, 1), (77, 0, 25.27571174516762, 0, 1, 4.9031248940982834, 2.5394870800169045, 0, 0), (72, 1, 21.870150888703403, 0, 0, 5.72772509737109, 3.603081453318575, 0, 0), (55, 1, 35.56535796284196, 0, 0, 2.3833721062799693, 2.501525781772574, 0, 1), (59, 0, 25.59345634121907, 0, 1, 7.939550847155906, 4.470497680530796, 0, 0), (72, 0, 26.294191968430727, 0, 1, 2.388451604036069, 0.1884869521133531, 0, 0), (63, 0, 33.42184362360455, 0, 0, 1.6885928936703531, 0.7405039931356372, 0, 0), (57, 1, 20.418495002269392, 0, 1, 3.0708774336024867, 0.0417735208606928, 0, 0), (79, 1, 15.59096465115841, 1, 0, 3.2314521727941727, 2.9039841492673784, 0, 1), (52, 0, 30.17735090221952, 0, 2, 5.5171237201996695, 4.583215513469581, 0, 1), (77, 0, 20.798677402899383, 1, 2, 4.473027562526006, 3.3588963512743297, 0, 1), (80, 0, 29.861908379654324, 0, 1, 3.773484772303117, 0.006422127634007, 0, 0), (63, 0, 27.419171471479235, 0, 1, 2.58226813259983, 0.6007962936781097, 0, 0), (68, 0, 18.410993813918328, 0, 2, 4.5776461270413416, 3.3756494292220984, 0, 1), (78, 0, 25.107969202607304, 0, 0, 2.059881841884732, 3.653395057641951, 1, 1), (61, 0, 25.70499037314037, 0, 1, 7.092961271407681, 2.609311476660894, 0, 0), (79, 0, 32.31090378310924, 0, 0, 4.18932977983946, 0.9600812548397442, 0, 0), (66, 0, 17.60274123460416, 1, 0, 5.637371014453994, 4.473809935062475, 0, 0), (70, 0, 33.108470428218524, 0, 0, 2.049792328259108, 0.5877862456046828, 0, 0), (63, 1, 29.459672925160227, 0, 1, 7.419953911261723, 4.95111267307537, 1, 1), (74, 0, 21.854016663995147, 1, 1, 0.5227910326875962, 1.047033569749668, 0, 0), (71, 0, 16.985484224724665, 0, 0, 8.525426448755004, 0.05889938143321, 0, 0), (76, 0, 17.141456239910763, 0, 0, 1.9819638642166812, 4.9871146952677705, 1, 1), (56, 0, 19.796683117968573, 0, 0, 3.525292413005173, 3.3400972625628, 0, 0), (70, 1, 23.084289052888018, 1, 1, 7.226835744744866, 0.883411570881526, 0, 0), (58, 0, 27.97649477270676, 0, 1, 1.785197892725987, 3.351269880221796, 0, 1), (79, 0, 28.500297865112763, 0, 0, 9.437663822120143, 1.0560412929397582, 0, 0), (69, 1, 31.27193422617985, 0, 0, 3.762593293304219, 0.8942053425389968, 0, 0), (77, 0, 28.323944663783383, 1, 0, 9.232860210139355, 4.509580539189414, 0, 1), (72, 0, 31.737173879954756, 1, 0, 7.023987210805986, 2.2420392050796645, 0, 0), (66, 0, 33.26626275598115, 0, 1, 6.720595026617354, 2.190168283488234, 1, 1), (79, 0, 26.630140307092955, 0, 1, 0.5202375502944689, 4.305166999861202, 1, 1), (63, 1, 29.057420396947744, 0, 0, 0.0391837495109326, 0.7861783254711674, 0, 1), (80, 0, 38.9406321126345, 0, 1, 9.994606810596732, 3.453113710406708, 1, 1), (66, 0, 32.25012227051664, 0, 1, 7.867230147335408, 3.253032616260517, 1, 1), (54, 0, 20.02334221647641, 0, 0, 5.097260752881797, 4.448437062858325, 0, 0), (55, 0, 26.25927340645463, 1, 0, 2.8467473884646366, 3.7533450714082734, 1, 1), (69, 1, 33.90408322238115, 1, 0, 3.759712219291391, 2.443024629389924, 0, 1), (59, 1, 23.68928810597455, 1, 0, 7.5631009698029406, 3.0161106782898184, 0, 1), (73, 0, 20.866052046386336, 0, 2, 1.0233217953406315, 0.2192342624831494, 0, 1), (61, 0, 24.982897895232703, 1, 0, 4.104987136973794, 1.633109528740044, 0, 0), (73, 1, 39.81208755395938, 0, 1, 6.374024812092216, 0.281666388996199, 0, 0), (63, 1, 28.023949431801057, 0, 1, 1.0840037271662273, 2.191493040165829, 1, 1), (53, 1, 30.589642200068997, 0, 0, 8.759330221862049, 1.313466549400026, 0, 0), (55, 0, 33.8817605124202, 0, 1, 1.6811809759772511, 3.4457167849016885, 0, 1), (67, 0, 34.55070219175965, 1, 1, 6.250915526865287, 1.5979471312999916, 0, 0), (79, 1, 24.003410186787978, 0, 1, 0.6290747601802393, 4.061586663570594, 0, 1), (76, 0, 17.191068669095962, 0, 0, 1.8734679132678889, 3.7620461660600464, 0, 0), (59, 0, 38.42394557577657, 0, 0, 0.3247077169174828, 3.766564659396285, 0, 1), (64, 0, 24.924537926857084, 1, 0, 1.3605623443164294, 2.384959576890875, 0, 0), (66, 1, 30.014858334015432, 0, 0, 1.5478603484611198, 0.1918077739398732, 1, 1), (72, 1, 27.891985692412444, 0, 1, 3.011755869973588, 3.107322113283923, 0, 1), (79, 0, 36.28562394362739, 0, 1, 4.889509264384521, 1.3871336740048956, 0, 0), (79, 1, 20.212762858933395, 1, 0, 4.074078813546854, 3.2140102508104125, 1, 1), (79, 1, 38.26488036609791, 0, 1, 9.865694907793266, 3.464005993149544, 0, 1), (64, 1, 17.909159947136903, 1, 1, 0.5592635012822567, 4.354837999312712, 0, 1), (60, 0, 35.43624271227979, 0, 1, 1.4218137638735162, 1.7116704123049535, 0, 0), (64, 1, 36.701417252686255, 0, 1, 0.5450927741371958, 4.414182453390396, 0, 1), (63, 0, 32.37377722256154, 0, 1, 3.188173228730047, 0.2671730119550858, 0, 0), (70, 0, 35.56201409085902, 0, 0, 9.70116886418432, 2.4121180079736444, 0, 0), (54, 0, 38.068929762834856, 0, 0, 7.8803514957502205, 3.736123225442935, 0, 0), (54, 1, 27.1765479704734, 0, 0, 2.97214113845096, 1.55851660746406, 0, 0), (52, 0, 30.15632344377444, 1, 0, 1.356266160073134, 1.531196226142002, 1, 1), (78, 0, 34.120245022574885, 1, 2, 1.456286467054234, 4.189206904527593, 0, 1), (61, 0, 27.56415191158606, 1, 0, 6.428065910861736, 4.405525741782829, 0, 1), (58, 1, 24.966575694307828, 1, 0, 7.827456742513867, 1.283308449479572, 1, 1), (77, 1, 18.659349804056227, 0, 0, 9.374811723991046, 2.9649237387774696, 0, 0), (60, 1, 24.188360557288284, 0, 0, 6.91927363266592, 4.679970895008888, 0, 0), (53, 0, 39.1455540288305, 0, 0, 7.032800540422505, 4.983416389673399, 1, 1), (52, 0, 25.8124469582533, 0, 0, 4.025263554901421, 3.7539511558989385, 0, 0), (67, 1, 22.79540332713149, 0, 1, 9.200400525459036, 3.223599886909088, 0, 0), (74, 1, 27.653546571006103, 1, 0, 6.502550710936616, 1.7764482160965938, 0, 1), (56, 0, 31.02065786725516, 1, 1, 2.5855726364024587, 2.770906277243994, 0, 1), (54, 1, 20.40095456273999, 1, 0, 3.372124904062858, 3.810163605195256, 0, 1), (63, 0, 30.48969887244574, 0, 1, 4.022604136835421, 2.6868959522192752, 0, 0), (59, 0, 31.255027309953835, 0, 1, 0.5122429640431325, 4.203925359695573, 0, 1), (54, 1, 34.519039651711, 0, 0, 4.009703266883518, 1.1853519558708905, 0, 0), (54, 0, 16.454094887636895, 0, 0, 7.728400834265034, 0.3618819659706124, 0, 0), (56, 0, 39.87165792924418, 0, 0, 8.031705116327311, 4.770658207855362, 0, 0), (66, 0, 16.444514024909164, 0, 0, 1.53412882389088, 1.1162770053468043, 0, 0), (74, 0, 22.58187868918989, 0, 0, 1.9038178629703475, 0.0267449434711142, 0, 0), (58, 0, 32.304033542353295, 0, 0, 1.0580502485651422, 4.515253265512577, 1, 1), (61, 1, 22.65634051966529, 0, 0, 5.7856393227935445, 2.6372823186086607, 0, 0), (79, 1, 30.59739590729096, 0, 0, 9.113418162164088, 0.7056305914966093, 0, 0), (70, 1, 25.65208459725929, 0, 2, 1.7449848639795518, 4.050700453727306, 0, 1), (51, 1, 18.267759418504987, 0, 0, 3.787033555811593, 0.4378728149311911, 0, 0), (58, 1, 37.16510538101167, 0, 0, 8.431448650297455, 3.16924909367662, 0, 1), (68, 0, 26.24461622053306, 0, 0, 6.442130159896179, 4.573082272575958, 0, 0), (71, 1, 19.865562795519125, 1, 0, 6.507243843338003, 1.043259565792155, 0, 0), (80, 1, 24.19398377193224, 0, 0, 8.668214856884891, 3.326364181184554, 0, 0), (51, 1, 25.353243813223173, 0, 1, 8.939730574625047, 0.3934928835375473, 0, 0), (56, 0, 34.23262234103349, 0, 0, 5.4412600196310095, 3.67976780257589, 0, 0), (58, 0, 25.40384995449404, 1, 0, 7.569268451270138, 2.3169550440232314, 0, 0), (64, 0, 27.03360379088309, 0, 0, 6.067162019700039, 2.997152710138109, 1, 1), (62, 1, 21.495330218625856, 0, 0, 7.974205539416643, 3.708189093088104, 0, 0), (55, 1, 18.427742643224978, 0, 1, 0.8613577154903629, 3.311859299563768, 0, 1), (51, 0, 20.38004680043094, 0, 0, 1.7397739952180358, 3.440588296031751, 0, 0), (78, 0, 21.030036439988532, 0, 0, 0.1808109220568543, 2.126782481349918, 0, 0), (70, 0, 39.39684387275135, 0, 1, 4.003298684107582, 1.236030368694384, 0, 0), (61, 1, 17.74340496693759, 0, 0, 8.3629131310246, 4.459101057033064, 0, 0), (64, 0, 28.698987224342325, 1, 2, 2.1546290727573005, 0.9822065761139293, 0, 1), (76, 1, 26.359433363999024, 0, 0, 1.2048182243846794, 3.069229725038621, 0, 1), (72, 1, 36.1089270684904, 0, 2, 8.515371718979257, 0.4385882085998216, 0, 1), (63, 0, 23.1168981722515, 0, 2, 5.008766058895992, 3.12350334703304, 0, 1), (63, 1, 33.433926934694995, 0, 1, 9.814214249220251, 1.412704318312218, 0, 0), (77, 1, 26.486169210149665, 0, 0, 3.5000686847317874, 2.519443983956368, 0, 1), (74, 0, 34.62541359592642, 0, 0, 9.283725519807918, 3.543828161728273, 0, 0), (58, 1, 34.67258465638238, 1, 0, 5.908662673951145, 1.6710766863005733, 0, 1), (52, 1, 22.88517239370032, 1, 1, 6.527281237772241, 0.128712048736081, 0, 0), (76, 0, 25.9400781013848, 0, 0, 3.645664275198644, 4.016522867590168, 0, 0), (76, 1, 36.021789485648064, 1, 0, 1.9494276897015983, 2.591091578179637, 0, 1), (71, 1, 15.960658724058124, 0, 0, 8.26867847173362, 2.2775084760961013, 0, 0), (60, 1, 26.53693661561835, 1, 0, 7.621875111940821, 4.396021687926913, 0, 1), (58, 1, 31.483848055144566, 0, 0, 2.0751149538487903, 4.723750401051059, 0, 1), (56, 1, 27.9602005486301, 0, 0, 4.52215100101718, 2.9071244743454354, 0, 1), (52, 1, 18.75422502042604, 0, 0, 1.4278563666788469, 2.744662622496688, 0, 1), (70, 0, 33.43584421803714, 1, 2, 3.894346800776733, 1.0966020060569104, 0, 1), (61, 1, 27.805548020316863, 0, 0, 9.517024063905373, 2.144437156751053, 0, 0), (63, 1, 32.00569448020883, 0, 0, 3.1972084933985423, 3.261320029718851, 0, 1), (78, 1, 32.908084701567056, 0, 0, 3.5018652433196107, 4.684267150455076, 1, 1), (73, 0, 16.802108399966833, 0, 1, 0.8325765805063212, 0.822626861964062, 0, 0), (51, 1, 16.781418194131465, 0, 0, 7.245579091588183, 1.167902171111796, 1, 1), (51, 1, 15.302711880872186, 1, 1, 3.1151229901398603, 1.3173672284692413, 0, 0), (60, 1, 33.43770898647517, 1, 0, 4.426548482604331, 0.6152606179516246, 0, 1), (71, 0, 23.83128521255161, 0, 2, 4.852667423426215, 4.93174961472081, 0, 1), (68, 0, 22.41338953219138, 0, 0, 7.779094067485368, 1.5760836868864303, 0, 0), (68, 1, 23.74258074364624, 0, 1, 3.823633310616279, 0.5765054516952467, 0, 0), (77, 0, 34.36633827952954, 0, 0, 4.431273453229146, 0.5349563058731166, 0, 0), (71, 1, 31.53426527676036, 0, 0, 3.761904687696221, 3.59729983834986, 0, 1), (58, 0, 19.35273338335211, 0, 0, 5.259465769014594, 1.2847614975423494, 0, 0), (68, 0, 34.1093165555434, 0, 1, 5.242547205377367, 0.2825784539837866, 0, 0), (56, 1, 21.6261607081251, 1, 0, 6.707273254426008, 0.5169746831502076, 0, 0), (68, 1, 15.52362402577282, 0, 0, 2.6943944630365504, 2.157540599238212, 0, 0), (75, 0, 17.054291686910684, 0, 1, 2.7752280490239256, 1.149591854308163, 0, 0), (78, 1, 22.386119436935505, 0, 2, 7.235345733310886, 1.2674687662859518, 0, 1), (68, 1, 34.23057869595334, 0, 1, 5.771866762233088, 4.702686505514738, 0, 1), (73, 1, 18.03466045398516, 0, 0, 5.095088732242019, 1.905734410173678, 1, 1), (56, 0, 34.3658445159447, 0, 0, 3.594238268308171, 3.63789661067472, 0, 0), (51, 0, 31.097606338528266, 1, 0, 0.8147389771294189, 2.2581949775941896, 0, 1), (52, 1, 28.25755333122896, 1, 0, 1.9333923361205216, 4.283649732529487, 1, 1), (72, 1, 22.32055091752412, 0, 0, 0.5270978985343899, 0.4752826841628221, 0, 0), (63, 1, 39.49925823397126, 0, 1, 0.3756622954398059, 1.0023452388317948, 0, 1), (51, 1, 29.56056645518116, 0, 1, 5.380946641211112, 1.0310135795088944, 0, 0), (51, 0, 35.29424470225344, 1, 0, 2.431245304226687, 0.7914312802954904, 0, 0), (74, 0, 31.411965183287567, 1, 0, 7.447507316299222, 2.27830410776546, 0, 0), (74, 1, 23.45668764986246, 1, 0, 1.8993474366102003, 3.459319540804222, 1, 1), (75, 1, 20.615390296096297, 0, 0, 2.862798621119409, 4.345495343623643, 0, 0), (78, 0, 24.304175595937835, 1, 2, 2.474629812331464, 2.841595755389628, 0, 1), (57, 1, 25.985124742361304, 0, 0, 6.509717452185445, 0.3362031702601831, 0, 0), (71, 0, 21.017317795812623, 1, 0, 0.7308509102615024, 3.0727050911065774, 1, 1), (53, 0, 18.03753440752295, 0, 2, 2.736663849214577, 4.160812268645592, 0, 1), (67, 1, 22.147669730979004, 0, 2, 0.0735782962541453, 1.516097733592956, 0, 1), (52, 1, 36.5342499090859, 1, 1, 0.3752865753180312, 3.951299519708469, 1, 1), (79, 0, 37.97316334098886, 0, 1, 9.207708496360754, 2.478269604416236, 0, 0), (78, 0, 21.30602550433404, 0, 0, 9.68419130500408, 2.105594522170408, 0, 0), (79, 0, 31.404045942026787, 0, 1, 4.657255776674976, 0.9906537091178852, 0, 0), (78, 1, 19.43571923674267, 0, 0, 2.402450184643039, 0.0460044881268972, 0, 0), (55, 1, 28.62567297242346, 0, 0, 4.698043214486816, 3.136292003179891, 0, 1), (51, 1, 33.14949774963239, 0, 1, 8.30202884345762, 0.0422574803123027, 0, 0), (71, 0, 20.3377841577668, 0, 0, 3.3836786592521584, 0.1599723007216236, 0, 0), (60, 0, 27.646317323795724, 0, 0, 9.355230227588573, 4.700899173646207, 0, 0), (52, 0, 36.01757570028, 0, 0, 9.12207571249182, 4.460371755468104, 1, 1), (59, 1, 33.320038619156264, 1, 0, 2.093483993840988, 2.677609580429818, 0, 1), (58, 0, 28.555930137296208, 1, 1, 0.3941758512036297, 2.7179778745564604, 0, 1), (59, 0, 27.709013672907, 0, 1, 8.276102613491533, 1.9352500596744349, 0, 0), (76, 0, 36.83307289652019, 0, 0, 5.300523392123808, 2.286152098097722, 0, 0), (69, 1, 34.02803842607895, 0, 0, 2.4665644684477783, 4.439088201679095, 0, 1), (61, 1, 21.166971613040577, 0, 1, 7.426359896816905, 1.9704182425501595, 0, 0), (54, 0, 33.16154287782512, 0, 0, 2.7976693088704083, 1.5830121741370644, 0, 0), (79, 1, 17.479452489680398, 0, 0, 0.8814224339079213, 0.7524774903629278, 1, 1), (67, 1, 20.10089086572247, 0, 0, 6.93400853429044, 2.2076700518944845, 0, 0), (76, 1, 28.877123732557155, 1, 0, 9.90642737172179, 2.4530678794909955, 0, 1), (71, 1, 33.32678240074187, 1, 0, 2.7789112598775603, 4.243837926406571, 0, 1), (79, 0, 30.39963625650448, 1, 0, 4.981892991739791, 3.530290573190154, 0, 1), (68, 1, 19.7006183653854, 1, 0, 3.295304137739967, 2.452272042598924, 0, 0), (67, 1, 28.855662853300416, 0, 0, 6.842090751884866, 2.885102008452792, 0, 1), (56, 0, 15.882783873505977, 0, 0, 8.73361117841438, 4.01566544468123, 0, 0), (51, 0, 33.6433445682808, 1, 2, 0.5976227417838442, 0.2207278104372773, 0, 1), (78, 1, 20.062014004130937, 1, 0, 8.885992804371524, 4.9604609351441, 0, 1), (74, 0, 38.9518370029845, 1, 2, 3.290737794607279, 0.6517583985739589, 0, 1), (60, 1, 23.173290408451976, 0, 1, 5.120885766986639, 1.9738765838584145, 0, 0), (54, 0, 18.72220125831112, 0, 0, 9.406901877232318, 2.4610809164373344, 0, 0), (67, 0, 36.916269045705015, 0, 0, 3.522309750707453, 2.064555947946066, 0, 0), (73, 0, 37.154894511626864, 0, 0, 3.855525014916693, 3.4029154645938364, 0, 0), (75, 0, 29.826108354669604, 0, 0, 9.154162014667037, 0.6063244667956835, 0, 0), (52, 0, 24.788142454445733, 0, 1, 7.619343757430971, 0.5688097940227471, 0, 0), (71, 0, 32.39045366242017, 1, 2, 9.883705667215713, 3.2391851930411324, 1, 1), (68, 0, 30.489733436496017, 1, 0, 0.5823783082027523, 0.8922533704918739, 0, 1), (55, 0, 34.8549332819271, 1, 0, 4.360704802193126, 4.701985169727721, 1, 1), (57, 1, 17.324765995578304, 0, 0, 1.569026241461201, 1.3033319128105083, 0, 0), (59, 1, 29.705056673709763, 0, 0, 9.47565126324043, 4.266732488043619, 0, 1), (54, 0, 31.05813814763069, 1, 1, 2.6828720042777263, 3.862612958812722, 0, 1), (67, 0, 16.62133986207421, 0, 2, 5.908045335179159, 0.8441680332628504, 0, 0), (54, 1, 29.03711469898809, 1, 0, 9.41278928906798, 3.8462527962079336, 0, 1), (65, 0, 35.12472499201924, 0, 0, 5.62144753827585, 0.6094460604017948, 0, 0), (73, 1, 27.45639205658634, 1, 1, 1.2613765801615209, 1.7966949525789362, 0, 1), (54, 1, 16.926456978358278, 1, 1, 5.295336150224575, 2.3767953384043428, 0, 0), (80, 0, 23.355957967401523, 0, 0, 0.2103690246046863, 3.205030286603506, 0, 0), (60, 1, 34.62242442778669, 0, 1, 7.228392039002123, 4.506296038982817, 0, 1), (55, 0, 32.6920233685229, 1, 0, 0.3248659669016496, 0.8196013102347244, 0, 1), (52, 0, 34.71537411681016, 1, 1, 5.952768411040545, 1.907044049515617, 0, 0), (52, 0, 26.004974948887263, 1, 1, 9.688146905778044, 3.12471885203916, 1, 1), (67, 0, 25.85048415434688, 0, 1, 5.516879678064617, 1.3943596313048243, 0, 0), (75, 0, 20.51529881778028, 0, 0, 9.9684928428144, 0.316313359103374, 0, 0), (52, 1, 31.06412998837979, 0, 0, 6.154289150329266, 3.3467417538139803, 0, 1), (67, 0, 25.5312013323518, 0, 1, 4.057144241809477, 4.157869629552263, 1, 1), (78, 0, 34.6412904520058, 0, 1, 3.4728847430569774, 0.1929578096906692, 0, 0), (70, 0, 17.958404773084684, 0, 0, 2.6522852250267457, 4.3944057295642605, 0, 0), (74, 0, 35.99505714089043, 0, 0, 9.487904976919182, 0.6448945396358263, 0, 0), (65, 1, 29.296806780679663, 0, 0, 8.114659391516817, 2.991530378480094, 0, 1), (57, 1, 19.611906328340982, 0, 2, 5.381210100398132, 1.3744782912854387, 1, 1), (57, 1, 24.05588604130721, 0, 1, 0.7055006370989458, 0.16399937138448, 1, 1), (64, 0, 23.362782218548304, 1, 2, 9.340329911306393, 2.101676945977495, 0, 1), (70, 1, 15.65491771330162, 0, 0, 7.663512805573902, 4.475500145331221, 0, 0), (73, 0, 15.60479409728388, 0, 0, 6.579499112045923, 4.913262057467846, 0, 0), (53, 1, 22.468139339719325, 1, 0, 7.139579478647715, 2.5812391160003023, 1, 1), (52, 1, 25.741420318473377, 0, 0, 1.1706441298186263, 3.787345253615515, 1, 1), (66, 1, 36.04833916979521, 0, 0, 1.268728280630933, 3.545903518972024, 0, 1), (52, 1, 19.65253544615693, 0, 2, 5.92493479176405, 1.0016991054822115, 0, 1), (79, 0, 26.45467216844732, 0, 1, 6.225753978327817, 3.441464992136275, 0, 0), (80, 0, 27.07422180213388, 1, 1, 0.1004698105483159, 1.0986137505519844, 0, 1), (67, 0, 18.3369993103986, 0, 0, 1.948404916553641, 2.193358484015244, 1, 1), (54, 1, 27.41152880888249, 0, 1, 3.836090403551584, 2.266308862629298, 0, 0), (68, 1, 25.921267565379488, 0, 1, 4.243720260536347, 3.9609496913762254, 0, 1), (63, 1, 34.13782247477774, 0, 2, 6.0379275728611805, 3.273878756421301, 0, 1), (65, 0, 33.784377150726144, 0, 0, 9.660214591302086, 0.58402053866976, 0, 0), (72, 0, 31.42387890667849, 0, 1, 1.3063438155735974, 1.3657981018497256, 0, 0), (54, 1, 16.72395040891053, 1, 0, 0.2583897222001119, 2.2766437490430107, 0, 1), (79, 1, 16.426368028781358, 0, 1, 2.217794919335464, 4.542187739361324, 1, 1), (60, 0, 22.05467686733, 1, 0, 7.804711383801549, 0.5224015837697904, 0, 0), (56, 0, 21.54264209339765, 0, 0, 2.0117523228887944, 3.601339619736978, 0, 0), (68, 0, 21.238654996237653, 0, 0, 0.0996923473451849, 4.612862024529, 1, 1), (65, 1, 21.79874315321577, 1, 1, 0.8476615442633317, 2.842361010784098, 0, 1), (72, 1, 33.98495656044909, 0, 0, 8.07625869562975, 1.8186276056784207, 0, 0), (54, 0, 34.417763923879534, 0, 1, 9.15138820404896, 1.2868272920081705, 0, 0), (79, 1, 16.63415393910963, 1, 0, 8.545154359107496, 3.467549185231602, 0, 1), (52, 0, 27.189279841834608, 0, 0, 6.831755632398181, 0.1985560378612361, 0, 0), (71, 1, 15.840340004582066, 0, 0, 0.5233285730066284, 4.19704018804636, 0, 1), (80, 0, 16.566330086383864, 0, 1, 7.828486179866575, 2.2408542351065925, 0, 0), (51, 1, 18.48113427793988, 1, 1, 7.990821457719544, 1.1061890990334184, 0, 0), (52, 1, 25.277390065017663, 1, 0, 2.3290183864948166, 3.861201379466383, 0, 1), (61, 0, 31.594742154389728, 0, 1, 1.5569259775593292, 4.470456846289228, 0, 1), (73, 0, 29.00420458654605, 0, 0, 2.117981498815027, 4.209043545144095, 0, 0), (77, 0, 38.420561550827294, 0, 2, 7.925397676213367, 4.006760291351243, 1, 1), (59, 1, 25.46983297685404, 0, 2, 0.6665982982330609, 1.150422459287375, 0, 1), (65, 1, 21.50394477405128, 0, 0, 9.985608065856288, 2.0304106627988547, 0, 0), (69, 0, 39.53242726243117, 1, 0, 8.352440601588656, 1.1381626790969617, 0, 0), (51, 1, 21.413251561106197, 1, 1, 3.653668415506528, 2.6221817292887466, 1, 1), (66, 0, 31.354365036851863, 0, 0, 8.416154597578153, 4.030483739803738, 1, 1), (61, 0, 30.213181817411662, 0, 0, 0.7

In [18]:
df2[df2['Age']>50]

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory,Diagnosis
0,58,1,16.085313,0,1,8.146251,4.148219,1,1
1,71,0,30.828784,0,1,9.361630,3.519683,0,0
4,62,1,35.479721,0,0,5.356890,3.309849,0,1
6,80,1,20.701994,0,0,8.482031,3.152943,0,0
8,58,1,30.274525,0,1,4.719025,0.943161,1,1
...,...,...,...,...,...,...,...,...,...
1494,79,1,17.832588,0,0,5.909161,4.880353,0,1
1495,62,1,25.090025,0,0,9.892167,1.284158,0,1
1497,63,1,32.613861,1,1,0.466848,0.150101,0,1
1498,55,0,25.568216,0,0,7.795317,1.986138,1,1
1499,67,1,23.663104,0,0,2.525860,2.856600,1,0

In [19]:
db3.run("SELECT * FROM diabetes where age>50;")

'[(2, 197, 70, 45, 543, 30.5, 0.158, 53, 1), (8, 125, 96, 0, 0, 0.0, 0.232, 54, 1), (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0), (1, 189, 60, 23, 846, 30.1, 0.398, 59, 1), (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1), (11, 143, 94, 33, 146, 36.6, 0.254, 51, 1), (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0), (5, 109, 75, 26, 0, 36.0, 0.546, 60, 0), (4, 111, 72, 47, 207, 37.1, 1.39, 56, 1), (9, 171, 110, 24, 240, 45.4, 0.721, 54, 1), (8, 176, 90, 34, 300, 33.7, 0.467, 58, 1), (2, 109, 92, 0, 0, 42.7, 0.845, 54, 0), (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1), (4, 146, 92, 0, 0, 31.2, 0.539, 61, 1), (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0), (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1), (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0), (5, 147, 78, 0, 0, 33.7, 0.218, 65, 0), (8, 181, 68, 36, 495, 30.1, 0.615, 60, 1), (6, 103, 72, 32, 190, 37.7, 0.324, 55, 0), (8, 196, 76, 29, 280, 37.5, 0.605, 57, 1), (5, 162, 104, 0, 0, 37.7, 0.151, 52, 1), (7, 179, 95, 31, 0, 34.2, 0.164, 60, 0), (2, 158, 90, 0, 0, 31.6, 0.805, 66, 1), (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0), (7, 181, 84, 21, 192, 35.9, 0.586, 51, 1), (11, 155, 76, 28, 150, 33.3, 1.353, 51, 1), (3, 142, 80, 15, 0, 32.4, 0.2, 63, 0), (13, 106, 70, 0, 0, 34.2, 0.251, 52, 0), (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0), (2, 108, 80, 0, 0, 27.0, 0.259, 52, 1), (7, 136, 74, 26, 135, 26.0, 0.647, 51, 0), (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0), (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0), (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1), (8, 95, 72, 0, 0, 36.8, 0.485, 57, 0), (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0), (5, 103, 108, 37, 0, 39.2, 0.305, 65, 0), (4, 146, 78, 0, 0, 38.5, 0.52, 67, 1), (12, 140, 82, 43, 325, 39.2, 0.528, 58, 1), (5, 144, 82, 26, 285, 32.0, 0.452, 58, 1), (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0), (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0), (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0), (10, 148, 84, 48, 237, 37.6, 1.001, 51, 1), (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0), (0, 137, 84, 27, 0, 27.3, 0.231, 59, 0), (4, 132, 86, 31, 0, 28.0, 0.419, 63, 0), (0, 173, 78, 32, 265, 46.5, 1.159, 58, 0), (8, 194, 80, 0, 0, 26.1, 0.551, 67, 0), (6, 166, 74, 0, 0, 26.6, 0.304, 66, 0), (7, 195, 70, 33, 145, 25.1, 0.163, 55, 1), (8, 120, 78, 0, 0, 25.0, 0.409, 64, 0), (9, 91, 68, 0, 0, 24.2, 0.2, 58, 0), (9, 145, 88, 34, 165, 30.3, 0.771, 53, 1), (7, 125, 86, 0, 0, 37.6, 0.304, 51, 0), (6, 129, 90, 7, 326, 19.6, 0.582, 60, 0), (0, 57, 60, 0, 0, 21.7, 0.735, 67, 0), (10, 90, 85, 32, 0, 34.9, 0.825, 56, 1), (5, 187, 76, 27, 207, 43.6, 1.034, 53, 1), (6, 114, 88, 0, 0, 27.8, 0.247, 66, 0), (8, 110, 76, 0, 0, 27.8, 0.237, 58, 0), (6, 125, 76, 0, 0, 33.8, 0.121, 54, 1), (2, 197, 70, 99, 0, 34.7, 0.575, 62, 1), (12, 121, 78, 17, 0, 26.5, 0.259, 62, 0), (8, 124, 76, 24, 600, 28.7, 0.687, 52, 1), (3, 176, 86, 27, 156, 33.3, 1.154, 52, 1), (7, 150, 78, 29, 126, 35.2, 0.692, 54, 1), (11, 127, 106, 0, 0, 39.0, 0.19, 51, 0), (10, 162, 84, 0, 0, 27.7, 0.182, 54, 0), (4, 145, 82, 18, 0, 32.5, 0.235, 70, 1), (8, 91, 82, 0, 0, 35.6, 0.587, 68, 0), (9, 156, 86, 0, 0, 24.8, 0.23, 53, 1), (5, 136, 82, 0, 0, 0.0, 0.64, 69, 0), (1, 168, 88, 29, 0, 35.0, 0.905, 52, 1), (10, 94, 72, 18, 0, 23.1, 0.595, 56, 0), (5, 97, 76, 27, 0, 35.6, 0.378, 52, 1), (2, 105, 75, 0, 0, 23.3, 0.56, 53, 0), (0, 123, 72, 0, 0, 36.3, 0.258, 52, 1), (6, 190, 92, 0, 0, 35.5, 0.278, 66, 1), (10, 101, 76, 48, 180, 32.9, 0.171, 63, 0)]'

In [20]:
df3[df3['Age']>50]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
719,5,97,76,27,0,35.6,0.378,52,1
734,2,105,75,0,0,23.3,0.560,53,0
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
763,10,101,76,48,180,32.9,0.171,63,0

In [ ]:
import os
from langchain_openai import ChatOpenAI


os.environ['GITHUB_TOKEN'] = "..."  # Replace with your actual GitHub token
token = os.environ.get("GITHUB_TOKEN")
endpoint = "https://models.github.ai/inference"
model_name = "openai/gpt-4.1-mini" 

if not token:
    raise ValueError("GITHUB_TOKEN environment variable not set. Please provide a valid token.")

llm =ChatOpenAI(
    model_name=model_name,
    openai_api_key=token,
    openai_api_base=endpoint,
    temperature=0.5,
)

In [22]:
from langchain_community.agent_toolkits import create_sql_agent

agent_tool1 = create_sql_agent(llm, db=db1, agent_type="openai-tools", verbose=True)

agent_tool2 = create_sql_agent(llm, db=db2, agent_type="openai-tools", verbose=True)

agent_tool3 = create_sql_agent(llm, db=db3, agent_type="openai-tools", verbose=True)

In [23]:
agent_tool1.invoke({"input": "Tell me how many patients are over 50 years old?"})

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


heart_disease
Invoking: `sql_db_schema` with `{'table_names': 'heart_disease'}`



CREATE TABLE heart_disease (
	age BIGINT,
	sex BIGINT,
	cp BIGINT,
	trestbps BIGINT,
	chol BIGINT,
	fbs BIGINT,
	restecg BIGINT,
	thalach BIGINT,
	exang BIGINT,
	oldpeak FLOAT,
	slope BIGINT,
	ca BIGINT,
	thal BIGINT,
	target BIGINT
)

/*
3 rows from heart_disease table:
age	sex	cp	trestbps	chol	fbs	restecg	thalach	exang	oldpeak	slope	ca	thal	target
52	1	0	125	212	0	1	168	0	1.0	2	2	3	0
53	1	0	140	203	1	0	155	1	3.1	0	0	3	0
70	1	0	145	174	0	1	125	1	2.6	0	0	3	0
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;'}`


SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;'}`


[(710,)]There are 710 patients in the database who are over 50 years old.

> Finished chain.

{'input': 'Tell me how many patients are over 50 years old?',
 'output': 'There are 710 patients in the database who are over 50 years old.'}

In [28]:
agent_tool2.invoke({"input": "Tell me how many patients are over 50 years old?"})

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


cancer
Invoking: `sql_db_schema` with `{'table_names': 'cancer'}`



CREATE TABLE cancer (
	"Age" BIGINT,
	"Gender" BIGINT,
	"BMI" FLOAT,
	"Smoking" BIGINT,
	"GeneticRisk" BIGINT,
	"PhysicalActivity" FLOAT,
	"AlcoholIntake" FLOAT,
	"CancerHistory" BIGINT,
	"Diagnosis" BIGINT
)

/*
3 rows from cancer table:
Age	Gender	BMI	Smoking	GeneticRisk	PhysicalActivity	AlcoholIntake	CancerHistory	Diagnosis
58	1	16.085313321370478	0	1	8.146250560259173	4.148219026764642	1	1
71	0	30.82878438985056	0	1	9.361630415509964	3.519683335172577	0	0
48	1	38.78508355516642	0	2	5.1351786674177005	4.728367685254023	0	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS PatientsOver50 FROM cancer WHERE Age > 50;'}`


SELECT COUNT(*) AS PatientsOver50 FROM cancer WHERE Age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS PatientsOver50 FROM cancer WHERE Age > 50;'}`


[(757,)]There are 757 patients who are over 50 years old in the database.

> Finished chain.

{'input': 'Tell me how many patients are over 50 years old?',
 'output': 'There are 757 patients who are over 50 years old in the database.'}

In [30]:
agent_tool3.invoke({"input": "Tell me how many patients are over 50 years old?"})

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


diabetes
Invoking: `sql_db_schema` with `{'table_names': 'diabetes'}`



CREATE TABLE diabetes (
	"Pregnancies" BIGINT,
	"Glucose" BIGINT,
	"BloodPressure" BIGINT,
	"SkinThickness" BIGINT,
	"Insulin" BIGINT,
	"BMI" FLOAT,
	"DiabetesPedigreeFunction" FLOAT,
	"Age" BIGINT,
	"Outcome" BIGINT
)

/*
3 rows from diabetes table:
Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	Outcome
6	148	72	35	0	33.6	0.627	50	1
1	85	66	29	0	26.6	0.351	31	0
8	183	64	0	0	23.3	0.672	32	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS PatientsOver50 FROM diabetes WHERE Age > 50;'}`


SELECT COUNT(*) AS PatientsOver50 FROM diabetes WHERE Age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS PatientsOver50 FROM diabetes WHERE Age > 50;'}`


[(81,)]There are 81 patients over 50 years old in the database.

> Finished chain.

{'input': 'Tell me how many patients are over 50 years old?',
 'output': 'There are 81 patients over 50 years old in the database.'}

In [34]:
pip install -U ddgs

Collecting ddgs
  Downloading ddgs-9.11.3-py3-none-any.whl.metadata (14 kB)
Collecting click>=8.1.8 (from ddgs)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting primp==1.1.3 (from ddgs)
  Downloading primp-1.1.3-cp310-abi3-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: lxml>=4.9.4 in c:\users\iqbal\anaconda3\lib\site-packages (from ddgs) (5.2.1)
Requirement already satisfied: colorama in c:\users\iqbal\anaconda3\lib\site-packages (from click>=8.1.8->ddgs) (0.4.6)
Downloading ddgs-9.11.3-py3-none-any.whl (43 kB)
   ---------------------------------------- 0.0/43.7 kB ? eta -:--:--
   ---------------------------------------- 43.7/43.7 kB 2.2 MB/s eta 0:00:00
Downloading primp-1.1.3-cp310-abi3-win_amd64.whl (3.6 MB)
   ---------------------------------------- 0.0/3.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/3.6 MB 5.9 MB/s eta 0:00:01
   --- ------------------------------------ 0.3/3.6 MB 6.3 MB/s eta 0:00:01
   --- ------------------------------------ 0.3/3.6 MB 6.3 MB/s eta 0:00:01
   ------ --------------------------------- 0.6/3.6 MB 3.2 MB/s eta 0:00:01
   ------- -------------------------------- 0.6/3.6 MB 2.7 MB/s eta 0:00:02
   ------- -------------------------------- 0.6/3.6 MB 2.7 MB/s eta 0:00:02
   ---------- ----------------------------- 0.9/3.6 MB 3.0 MB/s eta 0:00:01
   ------------ --------------------------- 1.1/3.6 MB 3.2 MB/s eta 0:00:01
   -------------- ------------------------- 1.3/3.6 MB 3.3 MB/s eta 0:00:01
   ---------------- ----------------------- 1.5/3.6 MB 3.4 MB/s eta 0:00:01
   ----------------- ---------------------- 1.6/3.6 MB 3.3 MB/s eta 0:00:01
   ------------------ --------------------- 1.7/3.6 MB 3.1 MB/s eta 0:00:01
   ------------------ --------------------- 1.7/3.6 MB 3.1 MB/s eta 0:00:01
   ------------------- -------------------- 1.7/3.6 MB 2.8 MB/s eta 0:00:01
   -------------------- ------------------- 1.8/3.6 MB 2.7 MB/s eta 0:00:01
   -------------------- ------------------- 1.9/3.6 MB 2.6 MB/s eta 0:00:01
   --------------------- ------------------ 1.9/3.6 MB 2.6 MB/s eta 0:00:01
   ---------------------- ----------------- 2.0/3.6 MB 2.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.1/3.6 MB 2.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.1/3.6 MB 2.4 MB/s eta 0:00:01
   ------------------------ --------------- 2.2/3.6 MB 2.4 MB/s eta 0:00:01
   ------------------------ --------------- 2.2/3.6 MB 2.3 MB/s eta 0:00:01
   ------------------------- -------------- 2.3/3.6 MB 2.2 MB/s eta 0:00:01
   ------------------------- -------------- 2.3/3.6 MB 2.3 MB/s eta 0:00:01
   ------------------------- -------------- 2.3/3.6 MB 2.2 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 2.1 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 2.1 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 2.0 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 1.9 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 1.9 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.6 MB 1.8 MB/s eta 0:00:01
   --------------------------- ------------ 2.4/3.6 MB 1.8 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.6 MB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.6 MB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.6 MB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.6 MB 1.6 MB/s eta 0:00:01
   --------------------------- ------------ 2.5/3.6 MB 1.6 MB/s eta 0:00:01
   ---------------------------- ----------- 2.5/3.6 MB 1.5 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.6 MB 1.5 MB/s eta 0:00:01
   ---------------------------- ----------- 2.6/3.6 MB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 2.6/3.6 MB 1.5 MB/s eta 0:00:01
   ----------------------------- ---------- 2.7/3.6 MB 1.5 MB/s eta 0:00:01
   ------------------------------ --------- 2.7/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.8/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.8/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------- -------- 2.8/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------- -------- 2.9/3.6 MB 1.4 MB/s eta 0:00:01
   -------------------------------- ------- 2.9/3.6 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.0/3.6 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.0/3.6 MB 1.4 MB/s eta 0:00:01
   --------------------------------- ------ 3.1/3.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------- ----- 3.1/3.6 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 3.2/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.3/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.3/3.6 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.6 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 3.5/3.6 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 3.5/3.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  3.6/3.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 3.6/3.6 MB 1.4 MB/s eta 0:00:00
Downloading click-8.3.1-py3-none-any.whl (108 kB)
   ---------------------------------------- 0.0/108.3 kB ? eta -:--:--
   ---------------------- ----------------- 61.4/108.3 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 108.3/108.3 kB 1.6 MB/s eta 0:00:00
Installing collected packages: primp, click, ddgs
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
Successfully installed click-8.3.1 ddgs-9.11.3 primp-1.1.3
Note: you may need to restart the kernel to use updated packages.

In [24]:
from langchain.tools import tool
from langchain_community.tools import DuckDuckGoSearchRun

@tool
def heart_disease_db(question: str) -> str:
    """
    Use this tool to answer questions related to the heart disease database.
    """
    result = agent_tool1.invoke({"input": question})
    return result["output"]


@tool
def cancer_db(question: str) -> str:
    """
    Use this tool to answer questions related to the cancer database.
    """
    result = agent_tool2.invoke({"input": question})
    return result["output"]


@tool
def diabetes_db(question: str) -> str:
    """
    Use this tool to answer questions related to the diabetes database.
    """
    result = agent_tool3.invoke({"input": question})
    return result["output"]

search_tool = DuckDuckGoSearchRun()

In [25]:
try:
    # Try the new import path first (recommended)
    from langchain.agents import create_react_agent
except ImportError:
    # Fall back to langgraph if the above doesn't work
    from langgraph.prebuilt import create_react_agent

In [26]:
agent_executor = create_react_agent(
    model=llm, 
    tools=[heart_disease_db, cancer_db, diabetes_db, search_tool]
)

C:\Users\IQBAL\AppData\Local\Temp\ipykernel_29260\2232809678.py:1: LangGraphDeprecatedSinceV10: create_react_agent has been moved to `langchain.agents`. Please update your import to `from langchain.agents import create_agent`. Deprecated in LangGraph V1.0 to be removed in V2.0.
  agent_executor = create_react_agent(

In [38]:
# Run the agent
agent_executor.invoke({"messages": [("user", "Tell me how many patients are over 50 years old in diabetes database?")]})

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


diabetes
Invoking: `sql_db_schema` with `{'table_names': 'diabetes'}`



CREATE TABLE diabetes (
	"Pregnancies" BIGINT,
	"Glucose" BIGINT,
	"BloodPressure" BIGINT,
	"SkinThickness" BIGINT,
	"Insulin" BIGINT,
	"BMI" FLOAT,
	"DiabetesPedigreeFunction" FLOAT,
	"Age" BIGINT,
	"Outcome" BIGINT
)

/*
3 rows from diabetes table:
Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	Outcome
6	148	72	35	0	33.6	0.627	50	1
1	85	66	29	0	26.6	0.351	31	0
8	183	64	0	0	23.3	0.672	32	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS patients_over_50 FROM diabetes WHERE Age > 50;'}`


SELECT COUNT(*) AS patients_over_50 FROM diabetes WHERE Age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS patients_over_50 FROM diabetes WHERE Age > 50;'}`


[(81,)]There are 81 patients in the database who are over 50 years old.

> Finished chain.

{'messages': [HumanMessage(content='Tell me how many patients are over 50 years old in diabetes database?', additional_kwargs={}, response_metadata={}, id='64e462eb-9af9-4b7b-a9d0-770f35b6d05f'),
  AIMessage(content='', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 25, 'prompt_tokens': 169, 'total_tokens': 194, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4.1-mini-2025-04-14', 'system_fingerprint': 'fp_b6f445fc1c', 'id': 'chatcmpl-DId54ry6U5mbheaeRtqxrBkdWM8pu', 'finish_reason': 'tool_calls', 'logprobs': None}, id='lc_run--019ce2da-8eb6-7d51-be48-09b63cf51bd4-0', tool_calls=[{'name': 'diabetes_db', 'args': {'question': 'How many patients are over 50 years old?'}, 'id': 'call_r23kvVQXWQvO3znUJ9WopCsa', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 169, 'output_tokens': 25, 'total_tokens': 194, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}),
  ToolMessage(content='There are 81 patients in the database who are over 50 years old.', name='diabetes_db', id='b20faec4-2869-4699-94ec-66e613c7e0b1', tool_call_id='call_r23kvVQXWQvO3znUJ9WopCsa'),
  AIMessage(content='There are 81 patients over 50 years old in the diabetes database.', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 17, 'prompt_tokens': 218, 'total_tokens': 235, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4.1-mini-2025-04-14', 'system_fingerprint': 'fp_b6f445fc1c', 'id': 'chatcmpl-DId5J6stmKmzRmhvc1lnOs7veJ7Xo', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019ce2da-c9c0-7541-a9f4-19a80c19d53e-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 218, 'output_tokens': 17, 'total_tokens': 235, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})]}

In [39]:
# Run the agent
result = agent_executor.invoke({"messages": [("user", "Tell me how many patients are over 50 years old in diabetes database?")]})
# Extract the final answer
final_message = result['messages'][-1]
print("\nFinal Answer:", final_message.content)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


diabetes
Invoking: `sql_db_schema` with `{'table_names': 'diabetes'}`



CREATE TABLE diabetes (
	"Pregnancies" BIGINT,
	"Glucose" BIGINT,
	"BloodPressure" BIGINT,
	"SkinThickness" BIGINT,
	"Insulin" BIGINT,
	"BMI" FLOAT,
	"DiabetesPedigreeFunction" FLOAT,
	"Age" BIGINT,
	"Outcome" BIGINT
)

/*
3 rows from diabetes table:
Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	Outcome
6	148	72	35	0	33.6	0.627	50	1
1	85	66	29	0	26.6	0.351	31	0
8	183	64	0	0	23.3	0.672	32	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM diabetes WHERE Age > 50;'}`


SELECT COUNT(*) AS count_over_50 FROM diabetes WHERE Age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM diabetes WHERE Age > 50;'}`


[(81,)]There are 81 patients over 50 years old in the diabetes database.

> Finished chain.

Final Answer: There are 81 patients over 50 years old in the diabetes database.

In [40]:

result = agent_executor.invoke({"messages": [("user", "Tell me how many patients are over 50 years old in heart disease database?")]})
# Extract the final answer
final_message = result['messages'][-1]
print("\nFinal Answer:", final_message.content)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


heart_disease
Invoking: `sql_db_schema` with `{'table_names': 'heart_disease'}`



CREATE TABLE heart_disease (
	age BIGINT,
	sex BIGINT,
	cp BIGINT,
	trestbps BIGINT,
	chol BIGINT,
	fbs BIGINT,
	restecg BIGINT,
	thalach BIGINT,
	exang BIGINT,
	oldpeak FLOAT,
	slope BIGINT,
	ca BIGINT,
	thal BIGINT,
	target BIGINT
)

/*
3 rows from heart_disease table:
age	sex	cp	trestbps	chol	fbs	restecg	thalach	exang	oldpeak	slope	ca	thal	target
52	1	0	125	212	0	1	168	0	1.0	2	2	3	0
53	1	0	140	203	1	0	155	1	3.1	0	0	3	0
70	1	0	145	174	0	1	125	1	2.6	0	0	3	0
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;'}`


SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS count_over_50 FROM heart_disease WHERE age > 50;'}`


[(710,)]There are 710 patients over 50 years old in the heart disease database.

> Finished chain.

Final Answer: There are 710 patients over 50 years old in the heart disease database.

In [30]:


result = agent_executor.invoke({"messages": [("user", "What is the average glucose level in diabetes dataset?")]})
# Extract the final answer
final_message = result['messages'][-1]
print("\nFinal Answer:", final_message.content)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


diabetes
Invoking: `sql_db_schema` with `{'table_names': 'diabetes'}`



CREATE TABLE diabetes (
	"Pregnancies" BIGINT,
	"Glucose" BIGINT,
	"BloodPressure" BIGINT,
	"SkinThickness" BIGINT,
	"Insulin" BIGINT,
	"BMI" FLOAT,
	"DiabetesPedigreeFunction" FLOAT,
	"Age" BIGINT,
	"Outcome" BIGINT
)

/*
3 rows from diabetes table:
Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	Outcome
6	148	72	35	0	33.6	0.627	50	1
1	85	66	29	0	26.6	0.351	31	0
8	183	64	0	0	23.3	0.672	32	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT AVG(Glucose) AS Average_Glucose FROM diabetes;'}`


SELECT AVG(Glucose) AS Average_Glucose FROM diabetes;
Invoking: `sql_db_query` with `{'query': 'SELECT AVG(Glucose) AS Average_Glucose FROM diabetes;'}`


[(120.89453125,)]The average glucose level in the diabetes dataset is approximately 120.89.

> Finished chain.

Final Answer: The average glucose level in the diabetes dataset is approximately 120.89.

In [28]:
result = agent_executor.invoke({"messages": [("user", "How many cancer patients are female?")]})
# Extract the final answer
final_message = result['messages'][-1]
print("\nFinal Answer:", final_message.content)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


cancer
Invoking: `sql_db_schema` with `{'table_names': 'cancer'}`



CREATE TABLE cancer (
	"Age" BIGINT,
	"Gender" BIGINT,
	"BMI" FLOAT,
	"Smoking" BIGINT,
	"GeneticRisk" BIGINT,
	"PhysicalActivity" FLOAT,
	"AlcoholIntake" FLOAT,
	"CancerHistory" BIGINT,
	"Diagnosis" BIGINT
)

/*
3 rows from cancer table:
Age	Gender	BMI	Smoking	GeneticRisk	PhysicalActivity	AlcoholIntake	CancerHistory	Diagnosis
58	1	16.085313321370478	0	1	8.146250560259173	4.148219026764642	1	1
71	0	30.82878438985056	0	1	9.361630415509964	3.519683335172577	0	0
48	1	38.78508355516642	0	2	5.1351786674177005	4.728367685254023	0	1
*/
Invoking: `sql_db_query_checker` with `{'query': 'SELECT COUNT(*) AS FemaleCancerPatients FROM cancer WHERE Gender = 0 AND Diagnosis = 1;'}`


SELECT COUNT(*) AS FemaleCancerPatients FROM cancer WHERE Gender = 0 AND Diagnosis = 1;
Invoking: `sql_db_query` with `{'query': 'SELECT COUNT(*) AS FemaleCancerPatients FROM cancer WHERE Gender = 0 AND Diagnosis = 1;'}`


[(193,)]There are 193 female cancer patients in the database.

> Finished chain.

Final Answer: There are 193 female cancer patients in the database.

In [31]:
result = agent_executor.invoke({"messages": [("user", "Search latest treatment for diabetes")]})
# Extract the final answer
final_message = result['messages'][-1]
print("\nFinal Answer:", final_message.content)

Final Answer: The latest treatments for diabetes in 2024-2025 include new oral and injectable medications. Notably, there are expanded uses of GLP-1 receptor agonists for heart and kidney health, along with new dual-action medications. Two newer classes of medications that show promise in improving outcomes for type 2 diabetes are GLP-1 receptor agonists and SGLT-2 inhibitors. Despite the availability of multiple glucose-lowering agents, maintaining tight glycemic control remains a challenge for many people with type 2 diabetes. Research is ongoing to develop future non-insulin agents and therapeutic approaches to improve treatment outcomes. If you want, I can provide more specific details or information on any of these treatments.